# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

julia:
  - nightly

sudo: true

after_success:
  - if [[ "$TRAVIS_OS_NAME" == linux && "$TRAVIS_JULIA_VERSION" == nightly ]] ; then julia --project=. -e 'using Pkg;
                                                                                                           Pkg.add("Coverage");
                                                                                                           using Coverage;
                                                                                                           Codecov.submit(process_folder())' ; fi
